export default {
  SELECT_CATEGORY: "SELECT_CATEGORY",
  FETCH_CATEGORY_EMAILS: "FETCH_CATEGORY_EMAILS",
  FETCH_CATEGORY_EMAILS_SUCCESS: "FETCH_CATEGORY_EMAILS_SUCCESS",
  FETCH_CATEGORY_EMAILS_ERROR: "FETCH_CATEGORY_EMAILS_ERROR",
  SELECT_ALL_CATEGORY_EMAILS: "SELECT_ALL_CATEGORY_EMAILS",
  TOGGLE_CATEGORY_SELECTED_EMAILS: "TOGGLE_CATEGORY_SELECTED_EMAILS"
};
